### ISSUE TITLE
Light forest 1 cutscene

### ISSUE THREAD

**Issue by modelarious** [Cosmic-Cryptid-Games/GrowingDepths#103]

**Comment by Cvervoorst** [comment]
After the title screen the game opens from a first-person perspective of the God King of the Depths placing a small bundle onto the ground in front of them. Text appears at the bottom of the screen saying “Come find me at the centre of the depths and fulfill your destiny”. The game then cuts to the 2D perspective that the rest of the game will be in and players catch a glimpse of an imposing figure making its way off the right edge of the screen, heading deeper into the depths. The heir slowly and shakily stands up (like a newborn baby deer) and attempts to give chase, but after their first few steps they stumble. When the stumble occurs the foot of the God stops for an instant until the heir gains its footing and then moves off the screen. After the Heir stumble players gain control of the character and the game begins.
