### ISSUE TITLE
Clouds should regenerate after a short period of time

### ISSUE THREAD

**Issue by modelarious** [Cosmic-Cryptid-Games/GrowingDepths#276]
The player can survive falling in the section in the Treetops 7 where you need to jump across clouds.  The clouds should regenerate after.. 2 seconds?

**Comment by rye-f** [comment]
Sounds good

**Comment by modelarious** [comment]
Clouds will be in exactly one of three arrays that each represent one of three states: 
- Available/ticking down (player can interact with cloud)
- Cooldown (cloud is invisible and player can't interact with it)
- Fading in (cloud is becoming visible and player can interact)

`Cooldown` is 150 frames and `Fade in` period is 15 frames while the `Available` period is set by variable, but is usually 100 frames or 50 frames.

Transitions go as follows:

1. Starts in `Available`
2. Player lands on cloud
3. Starts ticking down and fading out cloud
4. Timer hits 0 and the cloud transitions into `Cooldown` phase in which it is invisible and can't be interacted with
5. Cooldown timer hits 0 and the cloud transitions into `Fading In`
6. Cloud can now be interacted with and is fading back in
7. Fade in timer hits `maxFadeInTimer` and transitions cloud back to `Available` state
