### ISSUE TITLE
Intro cutscene/ gameplay interruption

### ISSUE THREAD

**Issue by Stelvlen** [Cosmic-Cryptid-Games/GrowingDepths#312]
If the player press any key before the intro cutscene (or maybe right at the start of the intro), the cutscene will not play and the game will freeze in black screen, the player will need to press F5 or quit and reopen the game to play.
Playing the beta version on windows 10.

**Comment by modelarious** [comment]
This is pretty concerning! Thanks for pointing this out

**Comment by modelarious** [comment]
I can reproduce this by holding down a directional key when selecting "new game" on the title screen on OSX, but very infrequently
