### ISSUE TITLE
Double death triggered in a few cases

### ISSUE THREAD

**Issue by Stelvlen** [Cosmic-Cryptid-Games/GrowingDepths#315]
The player will trigger double death effect if they touch the bottom part of the squirrel when the squirrel is moving up/down. This can also be triggered by touching the bottom part of the owl when it's flying upward.
Playing the beta version on Windows 10.
Maybe we can introduce it as a function haha
"Achievement unlocked: Double death, twice the fun"

**Comment by modelarious** [comment]
Hopefully will be as easy as setting variable 4 (player currently dying) when they touch an enemy

**Comment by modelarious** [comment]
Also see #317

**Comment by modelarious** [comment]
This should be done by making the death reset common event set variable 4 to 1 when it starts

**Comment by modelarious** [comment]
Fixed this today
