### ISSUE TITLE
Fix first major walljump

### ISSUE THREAD

**Issue by modelarious** [Cosmic-Cryptid-Games/GrowingDepths#81]
put branch 2 blocks to the left

**Comment by rye-f** [comment]
This first one is ok if you use the dash at the end, is that not what we want the player to do?

**Comment by modelarious** [comment]
I agree, I don't think it needs fixing

**Comment by modelarious** [comment]
test comment..

**Comment by modelarious** [comment]
Maybe we should put mushrooms around where they should be making contact with the wall?

**Comment by modelarious** [comment]
After removing the ability to wall jump from the bottom of a wall with #128, it made sense to update this wall jump to be a little easier
